#!/usr/bin/env php
<?php
include("vendor/autoload.php");
use Symfony\Component\Console\Application;
use codeagent\treemap\site\PuzzlesCommand;
use codeagent\treemap\site\FakeCommand;
use codeagent\treemap\site\FilesystemCommand;

$application = new Application();
$application->add(new PuzzlesCommand());
$application->add(new FakeCommand());
$application->add(new FilesystemCommand());
$application->run();